name: e_commerce_bluestone
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http:
  provider:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans_7pt-Bold.ttf
        - asset: assets/fonts/NunitoSans_7pt-Regular.ttf
